### ISSUE TITLE
WALLC-S from Z-Wave.me same as Popp WALLC-S

### ISSUE THREAD

**Issue by bm480** [IcarusProject/me.zwave#12]
Last year I bought some additional WALLC-S switches, but they were labelled as Popp instead. However, I was able to succesfully add them to my OpenHab setup at that time, although the configuration parameters were slightly different. I also notice no difference in behaviour when trying to pair with Homey. Anyone can confirm that these are the same devices?

**Comment by priknr1** [comment]
Right now a new version of the zwave.me app is being committed to athom. So V0.12 should be in the appstore soon.
In this new version, there are 2 versions of the WALLC-S.
They have different manucaturer ID's The POPP version is the one added in the new version.

Zwave.me made is quite difficult to oversee things.
POPP, Reitz Group and probably some others all belong to Zwave-me now

**Comment by IcarusProject** [comment]
@bm480 Hass this issue been fixed by updating to the more recent version of both Homey and the Z-Wave.me app?

**Comment by bm480** [comment]
I haven't been able to pair any Wave devices, because I'm still on the stable branch (1.1.9). The fix for the pairing issue is in release 1.2.0 experimental. Hope it will be released soon... ;)

**Comment by bm480** [comment]
Actually, with Homey release 1.2.0 the pairing of WALLC-S devices was a no-brainer.

**Comment by priknr1** [comment]
@IcarusProject  this one can be closed. The other issue, is above my head. Are you up for it?

**Comment by IcarusProject** [comment]
This repository has moved. Please use https://github.com/priknr1/me.zwave to open up an issue.
