### ISSUE TITLE
Configuration problems for WALLC-S switch

### ISSUE THREAD

**Issue by bm480** [IcarusProject/me.zwave#19]
Hi, at last (that is, since Homey update 1.2) I'v been able to pair my WALLC-S devices. However, I have some issues when configuring the device.

1. For Button 1 and 3 pair mode the choice labels are too long to be read, e.g. when set to (2) Pair with double clicks. In pair button B/D are Up/Down correspondingly. Click is On/Off, Hold is dimming Up/Down. Single clicks works with... (incomplete sentence is shown).
2. With buttons setup in mode (2), group A/B/C/D set to On/Off/Dim any associations must be set for Groep 2/Groep 3 to be able to control 2 devices by association (I was expecting Groep 1/Groep 3 instead).
3. I'd like to have the double clicks processed by a Homey flow, but that doesn't seem possible. I've associated Groep 1/Groep 4 with node 1 (Homey) but I haven't been able to get a flow triggered. Also, when I double click a button it looks like it is treated as a single click, which I don't expect because the button mode is setup to send triggers for double clicks.

**Comment by priknr1** [comment]
I will have a look if I can shorten things for point 1.
 For point 3, have a look at this:
https://forum.athom.com/discussion/2949/how-to-double-click-zwave-me-wallc-s-wallc-2-makes-8-possible-options#latest

I dont really get what you mean at point 2, is this really an issue, or just something you expected differently?

**Comment by bm480** [comment]
To clarify point 2: it seems that we need to use Association Group 2 to associate button Group A and Association Group 3 to associate button Group C. This strikes me as somewhat unlogical, I'd expect Association Group 1 to be linked to button Group A. Apart from that associations for Group A/C seem to be working fine.
Point 3 actually refers to button Group B/D to be able to catch double clicks when the switch is configured with the correct pair mode: (2) Pair with double clicks. In pair button B/D are Up/Down correspondingly. I haven't been able to trigger a Homey flow for double clicks when the remaining association groups have been linked to node 1 (Homey).

**Comment by IcarusProject** [comment]
This repository has moved. Please use https://github.com/priknr1/me.zwave to open up an issue.
