### ISSUE TITLE
Unable to include ZME_WCD2

### ISSUE THREAD

**Issue by MbenzNo** [IcarusProject/me.zwave#21]
I am unable to include a wall controller. I am unsure what firmware version it is, but it is at least 3-4 years old. It is labelled ZME_WCD2 on the backside. I have excluded it from my Vera Network and tried to include it in Homey as WallC-S and WallC-S V2 without luck. 
To exclude/include it I have to set it in management mode and press button 3. It does not start inclusion with any other buttons. It is then detected, but after negotiation i get: No compatible Homey app found for this device.

Manual for the device:
http://www.benext.eu/static/manual/zwaveme/double-wall-controller-WCD2-white.pdf

**Comment by priknr1** [comment]
Hi,

First of all, this is not the correct repository, in the athom appstore, at the app, you can find the correct repository.  https://github.com/Priknr1/me.zwave

Please create a new issue there.  It doesnt matter how you try to include a z-wave device.  via the app, or even the z-wave button under homey,   it is all the same inclusion method, and after including, homey looks in all it's installed apps for a matching device.

If no matching device is found, the device will be added as generic device. When that is done, click the wrench symbol, go to Node information, anf find the Manufacturer ID, Device Type ID, and device ID. Include that info in the issue that you make in the right repository.

This is info needed, to add your device into the app.

@IcarusProject  Maybe after you see that @MbenzNo has opened an issue in the correct repository, you can delete this one?

**Comment by IcarusProject** [comment]
This repository has moved. Please use https://github.com/priknr1/me.zwave to open up an issue.
